/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Save Options": "保存选项",
    "Subreddit": "Subreddit",
    "The Gold Factory": "黄金工厂",
    "The Shop": "商店",
    "View inventory": "查看库存",
    "What do you want to buy, fellow adventurer?": "你想买什么，冒险家？",
    "You have eaten": "你已经吃了",
    "Your inventory:": "你的库存:",
    "You work here, and you are getting 1 gold bar per second as your salary.": "你在这里工作，你的工资是1金条/秒。",
    "You work here, and you get 1 gold bar per second as your salary.": "你在这里工作，你的工资是1金条/秒。",
    "Sorry, I have no more swords :(": "抱歉，我没有更多的剑了 :(",
    "Sorry, the stone sword is the best sword I have.": "对不起，这把石剑是我最好的剑了。",
    "A hole": "一个洞",
    "Another Shop": "另一个商店",
    "A sign": "一个标志",
    "by gamehelp16": "作者是 gamehelp16",
    "Change Theme": "更改主题",
    "Credits": "鸣谢",
    "Current weapon:": "当前武器:",
    "Fast Travel": "快速旅行",
    "gamehelp16's Dec 2021 Message": "gamehelp16的2021年12月的消息",
    "gold bar(s)": "金条",
    "Hi! Welcome to my shop! :D": "嗨！欢迎光临我的店！:D",
    "Inventory:": "库存:",
    "iron bar(s)": "铁条",
    "none": "无",
    "Not sure why you needed the sign to tell you that, but it must be important.": "我不知道你为什么需要这个标志来告诉你，但这一定很重要。",
    "Original game": "原始游戏",
    "This is an \"unfinished\" hole.": "这是一个“未完成”的洞。",
    "and receive a bonus!": "并获得一个奖励！",
    "for 2,500 gold bars and get more bars per second!": "需花费2500个金条，每秒获得更多的金条！",
    "- TGF: Regilded by voxelbugged -": "- TGF：由voxelbugged重制",
    "\"There is a hole here!\"": "“这儿有个洞！”",
    "Make your boss happier": "让你的老板更开心",
    "To make him happier and get some extra gold bars, you can do these things:": "为了让他更开心，并得到一些额外的金条，你可以做这些事情：",
    "No weapon?": "没有武器？",
    "Oh snap! It seems that you don't have a weapon, so you can't really kill the rats.": "哦，糟糕！看来你没有武器，所以你不能真正杀死老鼠。",
    "Decipher some messages": "破译一些信息",
    "Your boss loves cryptography, but he isn't very good at it. If you can help him, he promises to give you extra gold bars as a reward!": "你的老板喜欢密码学，但他不是很擅长。如果你能帮助他，他承诺给你额外的金条作为奖励！",
    "Don't worry, the price's the same no matter how many you buy at once!": "别担心，不管你一次买多少，价格都是一样的！",
    "gold bars / second": "金条 / 秒",
    "Iron Bars)": "铁条)",
    "mining machines.": "采矿机器。",
    "or": "或",
    "Production:": "生产:",
    "You are the boss! :o": "你说了算！:o",
    "You can also": "你也可以",
    "You currently have": "你现在有",
    "Your old boss left you a book with some codes. He promises to keep rewarding you, as long as you keep solving them!": "你以前的老板给你留了一本书，里面有密码。他承诺，只要你继续解决问题，他就会一直奖励你！",
    "Wooden Sword": "木剑",
    "Attacked!": "被攻击了！",
    "Thief": "盗贼",
    "This is you.": "这是你。",
    "VS": "VS",
    "Handmade Sword": "手工剑",
    "Wooden Sword": "木剑",
    "You": "你",
    "While you are digging the hole, someone suddenly runs towards you and attacks you!": "当你正在挖洞的时候，有人突然跑向你并袭击了你！",
    "\"A thief, nothing else.\"": "“一个小偷，仅此而已。”",
    "Stone Sword": "石剑",
    "Thanks!": "谢谢!",
    "Hi, I'm Andrew! Thanks for helping us kill the thief!": "嗨，我是安德鲁！谢谢你帮我们杀了那个小偷！",
    "By the way, I just finished setting up my new shop - maybe you'd want to buy something!": "顺便说一下，我刚开完新店，也许你想买点什么！",
    "Locked Gate": "上锁的大门",
    "This gate is locked. You probably need a key to unlock it.": "这个门是锁着的。你可能需要一把钥匙才能打开它。",
    "\"A monster\"": "\“一只怪物\”",
    "If you want to succeed in combat, you": "如果你想在战斗中获胜，你",
    "Monster": "怪物",
    "Monster!": "怪物!",
    "need": "需要",
    "Spatula??": "抹刀? ?",
    "There is a dangerous monster in the enchanting shop!": "附魔商店里有一个危险的怪物！",
    "Butter Sword!": "黄油剑！",
    "Castle": "城堡",
    "Castle Entrance": "城堡入口",
    "Castle Guard": "城堡守卫",
    "Castle Hall": "城堡大厅",
    "King's Room": "国王的房间",
    "You are entering the castle...": "你正在进入城堡...",
    "\"Guards the castle.\"": "“守卫城堡。”",
    "\"This ghost is guarding the chest.\"": "“这个幽灵守卫着箱子。”",
    "Ghost": "幽灵",
    "Invisible hands": "看不见的手",
    "The chest is guarded by a ghost!": "箱子被一个鬼魂守卫着！",
    "Whether you need help or just want some tips, feel free to give Us™ a call!": "无论您是需要帮助还是只是想要一些建议，请随时给我们打电话！",
    "Ring™, ring™, ring™!": "戒指™，戒指™，戒指™！",
    "a good supply of Health Potions. Trust Us™ on this one.": "充足的生命药水供应。在这一点上相信我们™。",
    "Hello, and thank you for calling the International Hint Hotline™!": "您好，感谢您拨打国际提示热线™！",
    "Their body": "他们的身体",
    "Rat!": "老鼠!",
    "Kill some rats": "击杀一些老鼠",
    "Kill it!!": "杀死它!",
    "A Rat": "老鼠",
    "Finding the rats is not a big deal - the problem is that these rats can fight back!": "找到老鼠不是什么大事——问题是这些老鼠会反击！",
    "\"An annoying rat.\"": "“一只讨厌的老鼠。”",
    "Goodbye, Rat!": "再见了，老鼠！",
    "Diamond Sword": "钻石剑",
    "Enchanting shop": "附魔商店",
    "Enchanting Shop": "附魔商店",
    "Iron Sword": "铁剑",
    "The owner of the enchanting shop gave you 1,000 gold bars as a reward for slaying the fearsome beast.": "附魔商店的老板给了你1000金条作为杀死可怕野兽的奖励。",
    "You can now visit the enchanting shop and enchant your sword!": "你现在可以访问附魔商店并附魔你的剑！",
    "gold bars)": "金条)",
    "of the shop.": "关于商店。",
    "Or, you can": "或者，你可以",
    "Welcome to the enchanting shop! Here, you can enchant your sword.": "欢迎来到附魔商店！在这里，你可以给你的剑附魔。",
    "Your sword is not enchanted. You should probably do something about that.": "你的剑没有附魔。你应该做点什么。",
    "Armor Section": "盔甲部分",
    "Your stats:": "你的属性：",
    "We sell armor too! Buy some to absorb damage from your enemies!": "我们也卖盔甲！买一些来吸收敌人的伤害！",
    "Worms": "虫子",
    "% damage absorbed": "% 伤害吸收",
    "Worms! :o": "虫子! :o",
    "There are worms under the ground!": "地下有虫子！",
    "They seem to be mad that you destroyed their home...": "你毁了他们的家，他们似乎很生气...",
    "Underground World!": "地下世界!",
    "Wow! You discovered an underground world! :o": "哇！你发现了一个地下世界！:o",
    "iron bar(s) /": "铁条 /",
    "Iron Mine": "铁矿山",
    "This iron mine allows you to get iron bars automatically!": "这个铁矿可以让你自动获得铁条！",
    "hour": "小时",
    "Gold Bars)": "金条)",
    "minute": "分钟",
    "Training Center": "训练中心",
    "Welcome to the training center!": "欢迎来到训练中心！",
    "Here, you can test your skills or learn a new one.": "在这里，你可以测试你的技能或学习一门新技能。",
    "Let's see how strong you are!": "让我看看你的实力！",
    "Test your skill!": "测试你的技能！",
    "Training Robot": "训练机器人",
    "\"A training robot\"": "“一个训练机器人”",
    "Skill level:": "技能等级:",
    "second(s))": "秒)",
    "Upgrade Skill": "升级技能",
    "You can now upgrade this skill in the training center!": "你现在可以在训练中心升级这个技能！",
    "Invulnerability": "刀枪不入",
    "Pick the skill that you want to learn.": "选择你想学的技能。",
    "Choose wisely, because changing it is expensive!": "明智地选择，因为改变它是昂贵的！",
    "Choose a skill": "选择一个技能",
    "Short ranged laser!": "短程激光！",
    "Thunder Bolt": "雷击",
    "damage)": "伤害)",
    "second": "秒",
    "Countdown 1 (You attack a little bit faster)": "倒计时1（你的攻击稍微快一点）",
    "Countdown 1 is the highest level of the countdown enchantment!": "倒计时1为倒计时附魔的最高等级！",
    "Sorry, I have no better boots for you.": "抱歉，我没有更好的 靴子 可以给你。",
    "Sorry, I have no better chestplate for you.": "抱歉，我没有更好的 板甲 可以给你。",
    "Sorry, I have no better helmet for you.": "抱歉，我没有更好的 头盔 可以给你。",
    "Sorry, I have no better pants for you.": "抱歉，我没有更好的 裤子 可以给你。",
    "Your sword is enchanted with:": "你的剑附魔了：",
    "A Chest!": "一个宝箱！",
    "The ancient scroll": "一个古老的卷轴",
    "You read the ancient scroll, it says:": "你阅读了古老的卷轴，上面写着：",
    "The chest contains 2,500 gold bars and an ancient scroll.": "箱子里有2500条金条和一个古老的卷轴。",
    "Empty": "空空如也",
    "The chest is empty now.": "现在箱子是空的。",
    "empty. There are 1,000 gold bars hidden inside the chest. :D": "空的。箱子里藏着1000金条。:D",
    "not": "不是",
    "I've told you! AGAIN!": "我告诉过你！再一次!",
    "Now I hate you.": "现在我恨你了。",
    "Oh, no, sorry, the chest is": "哦，不，抱歉，箱子",
    "PLEASE BELIEVE ME!!!": "请相信我!!!",
    "The chest is empty now, told ya before!": "The chest is empty now, told ya before!",
    "The chest is empty now. For real.": "现在箱子是空的。说真的。",
    "THE CHEST IS EMPTY!!!!!": "宝箱是空的！！！！！",
    "Life 10 is the highest level of the life enchantment!": "生命10是生命附魔的最高等级！",
    "The underground world is a lot larger than you'd expect! There's still so much more to find, so get digging!": "地下世界比你想象的要大得多！还有很多东西等着我们去发现，所以开始挖掘吧！",
    "\"I AM THE BOSS!!\"": "“我是老大！！”",
    "\"The staff makes the castle look good.\"": "“这个职员使城堡看起来很漂亮。”",
    "Castle Staff": "城堡职员",
    "Sword-like-knife": "像剑一样的刀",
    "Yay!": "耶!",
    "You are in front of the king! :o": "你在国王面前！:o",
    "You are inside the castle...": "你在城堡里面...",
    "Zombie King": "僵尸王",
    "You have defeated the boss, and you have found 14 conveniently-shaped obsidian cubes!": "你打败了boss，并且找到了14个形状方便的黑曜石立方体！",
    "You have defeated the boss again! The cubes, however, are absent.": "你再次击败了Boss！然而，立方体却不见了。",
    "\"A Ghost, nothing else.\"": "“一个幽灵，没有别的。”",
    "\"A monster!\"": "“一个怪物！”",
    "\"Unholy moly!\"": "“可恶的家伙！”",
    "\"Unicorn!! Yay!!! :D\"": "\“独角兽!! 耶!!! :D”",
    "99% off!": "99折优惠！",
    "Airplane": "飞机",
    "End of the Nether": "地狱的尽头",
    "Horn": "号角",
    "In this laboratory, you can make potions from the resources you have.": "在这个实验室里，你可以用你拥有的资源制作药剂。",
    "Item(s) going to be mixed:": "将被混合的物品：",
    "Laboratory": "实验室",
    "What's up everybody, welcome back to my laboratory, where safety is number 1 priority!": "大家好，欢迎回到我的实验室，在这里安全是第一要务！",
    "Potions Guide": "药水指南",
    "This airplane is for sale.": "这架飞机正在出售。",
    "the airplane (50,000 iron bars)": "飞机（50000 铁条）",
    "Nether!": "地狱！",
    "Unicorn": "独角兽",
    "Welcome to the nether!": "欢迎来到地狱！",
    "The Devil": "恶魔",
    "You managed to get to the end of the nether, and you got 1 lava bucket.": "你设法到达地狱的尽头，你得到了1个熔岩桶。",
    "Wings": "翅膀",
    "Weakened Ghost": "虚弱的幽灵",
    "Spells": "法术",
    "Wizard": "巫师",
    "Pegasus": "飞马座",
    "Pitchfork": "干草叉",
    "\"A weakened ghost.\"": "\"一个虚弱的幽灵.\"",
    "\"The Pegasus is facing the wrong direction :/\"": "\“飞马座的方向不对：:/”",
    "Game autosaves in": "游戏自动保存于",
    "Here, you can save your progress, or change options relating to doing that.": "在这里，你可以保存你的进程，或者改变与此相关的选项。",
    "second(s)": "秒",
    "(Uses HTML5 Local Storage": "(使用HTML5本地存储",
    "A more detailed changelog can be found on": "更详细的变更日志可以在这里找到",
    "The airplane is now yours!": "飞机现在是你的了！",
    "You have an airplane now!": "你现在有飞机了！",
    "Fly!!!": "起飞!!!",
    "Are you ready to fly?": "你准备好起飞了吗？",
    "minute(s) left.": "分钟。",
    "Your plane is currently flying.": "你的飞机现在正在飞翔。",
    "Time left:": "剩余时间:",
    "Fly!": "飞翔！",
    "Big hand": "大手",
    "The Castle": "城堡",
    "Giant": "巨人",
    "You enter the castle and see a man standing inside.": "你走进城堡，看到一个人站在里面。",
    "The Fox": "狐狸",
    "Unknown": "未知",
    "You choose to attack the fox. For some reason.": "你选择攻击狐狸。出于某种原因。",
    "\"A fox!\"": "\“一只狐狸！\”",
    "A Scroll!": "一个卷轴!",
    "The house": "房子",
    "Sand": "沙子",
    "There is a lot of sand here. You have no idea who put it here, if anyone did.": "这里有很多沙子。你不知道是谁放的，如果真有人放的话。",
    "You can't see anything interesting inside the sand. Maybe if you had something to help you see better...": "你在沙子里看不到任何有趣的东西。如果你有什么东西能让你看得更清楚...",
    "You enter the house, and you see a computer in front of you...": "你走进房子，看到你面前有一台电脑...",
    "The fox dropped a scroll:": "狐狸掉落了一个个卷轴:",
    "Invisible Bot": "隐形机器人",
    "Invisible laser!": "隐形激光！",
    "Here is the invisible bot, good luck!": "这是隐形机器人，祝你好运！",
    "\"An invisible robot!\"": "\“一个隐形机器人！”\”",
    "Wow - I didn't expect you to actually do it! Well then, have some of my items, as promised!": "哇，我没想到你真的会这么做！好吧，那就照我说的拿我的东西吧！",
    "I also have this really cool shiny sword - I hope this can be useful to you!": "我也有这个非常酷的闪亮的剑-我希望这可以对你有用！",
    "Congratulations!": "恭喜！",
    "Emerald Sword": "翡翠剑",
    "Good luck out there!": "祝你好运！",
    "Windows has been shut down to": "电脑已经关机以                   ",
    "prevent damage to your computer.": "防止损坏您的计算机。                  ",
    "A problem has been detected and": "检测到一个问题，以及                ",
    "If this is the first time you've": "如果这是你第一次                  ",
    "seen this Stop error screen.": "看到这个停止错误屏幕。          ",
    "No More Items :(": "没有更多的物品了 :(",
    "The problem seems to be caused by": "导致这个问题的似乎是                  ",
    "Sorry, I have no more items to give you :(": "抱歉，我没有更多的东西可以给你了。:(",
    "Glasses!": "眼镜!",
    "You're amazing!": "你真了不起!",
    "You found some magical glasses!": "你找到了一些神奇的眼镜！",
    "These glasses allow you to see some mysterious things in the sand and travel quickly between realms.": "这些眼镜可以让你看到沙子里一些神秘的东西，并在不同的领域之间快速旅行。",
    "\"How it swims, no one knows.\"": "“它是怎么游泳的，没人知道。”",
    "Sand Shark": "沙鲨",
    "Surprise!": "惊喜!",
    "You got nothing :(": "你什么都没找到 :(",
    "You have found a wild sand shark! It won't let you flee!": "你找到了一条野生沙鲨！它不会让你逃跑的！",
    "Someone": "某人",
    "Someone is standing there...": "有人站在那里...",
    "You start to bury yourself inside the sand, when you suddenly fall into a hole!": "你开始把自己埋在沙子里，突然你掉进了一个洞里！",
    "\"Abrakadabra!\"": "“阿布拉卡达布拉！”",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Status: ": "状态: ",
    "Code #": "编码 #",
    "Damage: ": "伤害: ",
    "Weapon: ": "武器: ",
    "(Game saved!)": "(游戏已保存!)",
    "Your skill is: ": "你的技能是：",
    "health potion ": "生命药水 ",
    "Gold bar ": "金条 ",
    "Iron bar ": "铁条 ",
    "lava bucket ": "岩浆桶 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " gold bar(s)": " 金条",
    " iron bar(s)": " 铁条",
    " lava bucket(s)": " 岩浆桶",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You killed the rat, and you found it hoarding (.+) gold bars!$/, '你杀了那只老鼠，却发现它囤积的 $1 金条！'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^Attack ([\d\.,]+) \(\+([\d\.,]+) damage\)$/, '攻击 $1 (+$2 伤害)'],
    [/^Life ([\d\.,]+) \(Heals ([\d\.,]+) HP each time you attack\)$/, '生命$1（每次攻击治疗 $2 生命）'],
    [/^([\d\.,]+) ancient scroll$/, '$1 古老的卷轴'],
    [/^([\d\.,]+) lava bucket$/, '$1 岩浆桶'],
    [/^([\d\.,]+) lava buckets$/, '$1 岩浆桶'],
    [/^([\d\.,]+) poison potion$/, '$1 毒药'],
    [/^([\d\.,]+) poison potions$/, '$1 毒药'],
    [/^([\d\.,]+) confusion potions$/, '$1 混乱药水'],
    [/^([\d\.,]+) confusion potion$/, '$1 混乱药水'],
    [/^([\d\.,]+) gambler\'s potions$/, '$1 赌徒药水'],
    [/^([\d\.,]+) gambler\'s potion$/, '$1 赌徒药水'],
    [/^([\d\.,]+) invisibility potions$/, '$1 隐形药水'],
    [/^([\d\.,]+) empty potions$/, '$1 空药水'],
    [/^([\d\.,]+) instant countdown potion$/, '$1 即时倒计时药水'],
    [/^([\d\.,]+) instant countdown potions$/, '$1 即时倒计时药水'],
    [/^([\d\.,]+) key$/, '$1 钥匙'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) pizzas$/, '$1 披萨'],
    [/^([\d\.,]+) shovel$/, '$1 铲子'],
    [/^([\d\.,]+) shovels$/, '$1 铲子'],
    [/^([\d\.,]+) health potion$/, '$1 生命药水'],
    [/^([\d\.,]+) health potions$/, '$1 生命药水'],
    [/^\(([\d\.,]+) sec\)$/, '($1 秒)'],
    [/^\(([\d\.,]+) Iron Bars\)$/, '($1 铁条)'],
    [/^\(([\d\.,]+) Gold Bars\)$/, '($1 金条)'],
    [/^\(([\d\.,]+) gold bars\)$/, '($1 金条)'],
    [/^\(([\d\.,]+) gold bars \+ stone sword\)$/, '($1 金条 + 石剑)'],
    [/^You got ([\d\.,]+) gold bars!$/, '你获得了 $1 金条！'],
    [/^You got ([\d\.,]+) iron bars!$/, '你获得了 $1 铁条！'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);